#Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'AiBasicApp' do
    #HTTP networking library
    pod 'Alamofire', '~> 4.5'
    #Auto Layout library
    pod 'SnapKit', '~> 4.0.0'
    #Promise
    pod 'PromiseKit', '~> 4.4'
end
